### PR TITLE
SJRK-342: The AIHEC logo still shows colours when a high contrast theme is selected

### PR DESCRIPTION
**Pull request by BlueSlug**
This update should be merged into `stories-aihec-production` once it has been merged into `master`

### CODE REVIEW

**Comment by BlueSlug** [comment]
Ready for more review

**Comment by gtirloni** [comment]
When this gets merged into master, it should trigger the new GitHub Actions workflow.

https://github.com/fluid-project/sjrk-story-telling/blob/master/.github/workflows/stories.floeproject.org__staging.yml

**Comment by cindyli** [comment]
When the high contrast theme is set to one of the last 3: Grey on white, Grey on dark, Black on brown, link colors are purple. They should match the selected foreground color.

Screen Shot 2020-04-28 at 4 23 07 PM

**Comment by cindyli** [comment]
When the high contrast theme is set to the last 2: Grey on dark, Black on brown, the background colors for UIO "hide preferences" and "reset" are different from the page background color.

With "Grey on dark", their background colors are black instead of dark grey:
Screen Shot 2020-04-28 at 4 27 38 PM

With "Black on brown", their background colors are a different tone of brown:
Screen Shot 2020-04-28 at 4 27 44 PM

**Comment by cindyli** [comment]
The issue above happens to the background color of buttons in the story editor:

Screen Shot 2020-04-28 at 4 31 52 PM

All high contrast issues occur across themes.

**Comment by cindyli** [comment]
Increasing the UIO text size breaks the styling on mobile devices. The increased width of buttons and text widths cause: 1. the horizontal overflow; 2. Texts stretch out of the view and become unreadable.

This is how the "browse stories" page looks on Galaxy S9:
Screen Shot 2020-04-28 at 4 38 55 PM

Smaller screens such as iphone 5 have worse results.

This issue happens across themes.

**Comment by cindyli** [comment]
> When this gets merged into master, it should trigger the new GitHub Actions workflow.
> 
> https://github.com/fluid-project/sjrk-story-telling/blob/master/.github/workflows/stories.floeproject.org__staging.yml

@gtirloni, when I push the master that has this .yml to my origin repo master branch, this workflow is also triggered and failed. Is it possible to have the workflow only triggered when pushing to the desired master at fluid-project/sjrk-story-telling but not the master from other repos? Thanks.

**Comment by gtirloni** [comment]
> @gtirloni, when I push the master that has this .yml to my origin repo master branch, this workflow is also triggered and failed. Is it possible to have the workflow only triggered when pushing to the desired master at fluid-project/sjrk-story-telling but not the master from other repos? Thanks.

You can disable GitHub Actions in the settings of your fork so they wouldn't run then.

**Comment by jobara** [comment]
> When the high contrast theme is set to one of the last 3: Grey on white, Grey on dark, Black on brown, link colors are purple. They should match the selected foreground color.

@cindyli, this is a feature. Those three themes are not binary. Admittedly this is a bit confusing compared the to the rest but they were adapted based on contrast themes from Windows. (See [FLUID-6298](https://issues.fluidproject.org/browse/FLUID-6298))

**Comment by jobara** [comment]
> You can disable GitHub Actions in the settings of your fork so they wouldn't run then.

@gtirloni and @cindyli, this would disable all GitHub Actions from running. Deploying to the production site is probably something we don't want forks doing. However being able to run tests and lint is actually quite useful in a fork. Perhaps we can look into job level conditionals to only run the deploy job when on the project repo ( see: https://github.blog/changelog/2019-10-01-github-actions-new-workflow-syntax-features/ ). For example we could check the [github context](https://help.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context) and only run if the `github.repository_owner` matches the organization (e.g. fluid-project).

**Comment by gtirloni** [comment]
> > You can disable GitHub Actions in the settings of your fork so they wouldn't run then.
> 
> @gtirloni and @cindyli, this would disable all GitHub Actions from running. Deploying to the production site is probably something we don't want forks doing. However being able to run tests and lint is actually quite useful in a fork. Perhaps we can look into job level conditionals to only run the deploy job when on the project repo ( see: https://github.blog/changelog/2019-10-01-github-actions-new-workflow-syntax-features/ ). For example we could check the [github context](https://help.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context) and only run if the `github.repository_owner` matches the organization (e.g. fluid-project).

I think that's a great idea! That way the CD workflows only run on this repo and the CI workflows can run anywhere (since they don't depend on our secrets). I'll submit a PR shortly. Thanks.

**Comment by BlueSlug** [comment]
> Increasing the UIO text size breaks the styling on mobile devices. The increased width of buttons and text widths cause: 1. the horizontal overflow; 2. Texts stretch out of the view and become unreadable.
> 
> This is how the "browse stories" page looks on Galaxy S9:
> Screen Shot 2020-04-28 at 4 38 55 PM
> 
> Smaller screens such as iphone 5 have worse results.
> 
> This issue happens across themes.

This is a known issue and is captured by [SJRK-302](https://issues.fluidproject.org/browse/SJRK-302). I've added a comment and attached your screenshot so we don't lose track of this :)

**Comment by BlueSlug** [comment]
I have also filed [SJRK-349](https://issues.fluidproject.org/browse/SJRK-349) to eventually do some thorough UIO testing of all themes

**Pull request merged**
