### PR TITLE
SJRK-337: Created AIHEC theme based on Cities theme

### PR DESCRIPTION
**Pull request by BlueSlug**
After merging into `master`, this should subsequently be merged into a new branch called `stories-aihec-production`

### CODE REVIEW

**Comment by cindyli** [comment]
Please update `README.md` and `sjrk.storyTelling.server.config.json5.example` to reflect the addition of the new theme. Thanks.

**Comment by cindyli** [comment]
Please add the new theme to https://github.com/BlueSlug/sjrk-story-telling/blob/SJRK-337/sjrk.storyTelling.server.config.json5.example#L18 too. Thanks.

**Comment by BlueSlug** [comment]
Whoops missed that one! On it :)

**Comment by cindyli** [comment]
I probably should have noticed earlier: there isn't any hover styling for buttons on cities, learningReflections, aihec themes. Probably with other themes too but I didn't go through all themes. I'm not sure if this is a design decision but it would be good to discuss with designers.

This doesn't need to be addressed in this pull request.

**Comment by BlueSlug** [comment]
Thanks @cindyli!

Re hover states, we have a Jira filed to take care of that at some point: https://issues.fluidproject.org/browse/SJRK-316

**Comment by cindyli** [comment]
> Re hover states, we have a Jira filed to take care of that at some point: https://issues.fluidproject.org/browse/SJRK-316

Great to know. Thanks.

**Pull request merged**
