### PR TITLE
SJRK-458 Bump Node.js to v14.16.0 (security release)

### PR DESCRIPTION
**Pull request by gtirloni**
https://issues.fluidproject.org/browse/SJRK-458

### CODE REVIEW

**Review by BlueSlug — CHANGES_REQUESTED** [review]
I recommend rebasing against main in order to get the tests working and passing again, but otherwise the change looks good! If it's all according to semver, nothing *should* break 😆

**Comment by gtirloni** [comment]
@BlueSlug thank you. I've rebased against main.

**Review by BlueSlug — APPROVED** [review]
Thanks, @gtirloni! The tests are passing again, and some quick testing of the docker-compose dev env (in HTTPS!) looked good 👍🏻

**Comment by jobara** [comment]
@gtirloni this didn't make it into the latest release. How critical is this for the deployed versions?

**Comment by gtirloni** [comment]
> @gtirloni this didn't make it into the latest release. How critical is this for the deployed versions?

It's hard to say but considering the deployment is behind a load balancer, that should shield us a little bit. I think we can wait until the next release.

**Comment by jobara** [comment]
merged at dc8379451a9e80596337f70ca883bb85cdb5e4bc

**Pull request merged**
