### PR TITLE
SJRK-397 Update Node.js to version 10.22.1

### PR DESCRIPTION
**Pull request by gtirloni**
To address vulnerabilities reported in the September security advisories.

https://nodejs.org/en/blog/vulnerability/september-2020-security-releases/

### CODE REVIEW

**Comment by gtirloni** [comment]
Docker images are still pending to be published. I'll re-run the CI job once they're available.

**Comment by jobara** [comment]
@BlueSlug could you please review/test this PR and if it looks good I can merge it in.

**Comment by BlueSlug** [comment]
@jobara I was successfully able to build and run the site via `docker-compose` locally, and the tests all passed without issue

**Comment by jobara** [comment]
@BlueSlug thanks for verifying that.

**Comment by jobara** [comment]
merged at a794568f48a828843f5bccbcc16dc243494edc28

**Pull request merged**
