### PR TITLE
SJRK-293: Update Production Floe stories site with latest Dev

### PR DESCRIPTION
**Pull request by BlueSlug**
The production FLOE Storytelling site is several months out of date with the current dev branch which has since had a number of styling updates and bug fixes. This also includes the major reorganization of the codebase completed in SJRK-237.

@cindyli will provide review.

Once the code has been merged into the production branch, or before if possible, the server config file (`sjrk.storyTelling.server.config.json5`) will need to be added to the container with the following settings:
```javascript
"globalConfig": {
    "port": "8081",
    "theme": "learningReflections",
    "themeIndexFile": "introduction.html",
    "authoringEnabled": false
}
```
@waharnum will have to add this file.

The [`editor_url` value](https://github.com/fluid-project/sjrk-story-telling/blob/stories-floe-dev/themes/learningReflections/messages/learningReflectionMessages_en.json#L3) in `learningReflectionsMessages_en.json` will also have to be updated to point to the [Staging Storytelling Tool's edit page](https://staging-stories.floeproject.org/storyEdit.html), as we don't want editing to be enabled on the production site. [SJRK-294](https://issues.fluidproject.org/browse/SJRK-294) has been filed to potentially store this value in the server config file in the future.
```javascript
"editor_url": "http://staging-stories.floeproject.org/storyEdit.html",
```

@carenwatkins will test the site once everything has been completed. The database backup job has already been run.

### CODE REVIEW

**Comment by cindyli** [comment]
Please resolve the conflict shown above.

**Comment by cindyli** [comment]
It might be worthwhile to create a JIRA to make "editor_url" configurable via the server config file and remove its definition from message bundle files.

**Comment by BlueSlug** [comment]
> It might be worthwhile to create a JIRA to make "editor_url" configurable via the server config file and remove its definition from message bundle files.

[SJRK-294](https://issues.fluidproject.org/browse/SJRK-294) was filed to handle this.

**Comment by waharnum** [comment]
I've added the needed configuration file to the container's volume directory.

I've also updated the CI job to contain the needed environment variable to reference to the config file: https://github.com/inclusive-design/ci-service/blob/master/jenkins_jobs/stack-stories.floeproject.org.yml

It should now be possible to merge this code and have the deployment work properly.

**Comment by BlueSlug** [comment]
Closing this PR in order to file a new one based on `stories-floe-production` that has the merge done by me.

**Pull request closed without merging**
